---
title: "Two Way Anova"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(GGally)

logit <- function(x)
{
  p <- x/2461
  return (log(p/(1-p)))
}
```

## Two Way ANOVA
Here is where we will do Two Way ANOVA, with League and Division as the two categorical variables.

```{r}
# will replace this when master .rmd file does transform.
hitters <- read_csv("Hitters.csv")
hitters$Division <- as.factor(hitters$Division)
hitters$League   <- as.factor(hitters$League)
for_anova <- hitters %>% filter(!is.na(Salary)) %>% select(Salary,Division,League) %>%
  mutate(logs = log(Salary),sqrts=sqrt(Salary),foo=logit(Salary),bar=1/Salary,aaa=log(bar))
```

```{r}
for_anova %>% ggpairs()
```

```{r}
ggplot(hitters,aes(x=League,y=Salary,group=Division,colour=Division)) + ylab("Salary") + xlab("League") + geom_point()
```

```{r}
hitters_aov.fit<-aov(logs~Division+League+Division:League,data=for_anova)
par(mfrow=c(1,2))
plot(hitters_aov.fit$fitted.values,hitters_aov.fit$residuals,ylab="Resdiduals",xlab="Fitted")
qqnorm(hitters_aov.fit$residuals)
```
